### ISSUE TITLE
Pontoon tools links to non-existing webpage after installation

### ISSUE THREAD

**Issue by zelitomas** [MikkCZ/pontoon-tools#37]
![snimek z 2017-09-19 09-52-08](https://user-images.githubusercontent.com/3105674/30581592-fdfdb124-9d20-11e7-9863-6900e001af12.png)

Link cz_CS on screenshot leads to URL https://pontoon.mozilla.org/cs_CZ/, which throws 404.

Fedora 26, Firefox 55, in Czech

**Comment by MikkCZ** [comment]
That's weird. Firefox should never be cs_CZ. Can you please open `about:debugging`, enable add-ons debugging, click debugging link for Pontoon Tools and check what `chrome.i18n.getUILanguage()` returns?
Also what is value do you see for `general.useragent.locale` preference in `about:config`?

**Comment by MikkCZ** [comment]
This will be probably solved by #24 in the future, but still I wonder, how cs_CZ could get there.

**Comment by zelitomas** [comment]
```getUILanguage()``` returns ```cs_CZ```, and in ```general.useragent.locale``` is ```cs-CZ``` (notice the hyphen instead of underscore). According to ```about:config``` the preference in default state: 

![snimek z 2017-09-20 14-25-20](https://user-images.githubusercontent.com/3105674/30643670-1dc33de0-9e10-11e7-88a3-4c7d3c7ed4e9.png)

Here is log from JS console: (not sure if everything is related to your addon though)

```
Funkci getElementById() předán prázdný řetězec.  github-32444a99dc2bd60e06b9dd497b0e5fd2ffd6f85165e93c589c165f75bedcf718.js:7:28475
Zdroj na „https://www.google-analytics.com/r/collect“ byl zablokován, protože je povolena ochrana proti sledování.[Learn More]  28
Content Security Policy: Ignorování „x-frame-options“ pro direktivu „frame-ancestors“. (unknown)
Funkci getElementById() předán prázdný řetězec.  github-32444a99dc2bd60e06b9dd497b0e5fd2ffd6f85165e93c589c165f75bedcf718.js:7:28475
Zdroj na „https://www.google-analytics.com/collect“ byl zablokován, protože je povolena ochrana proti sledování.[Learn More]  MikkCZ
Funkci getElementById() předán prázdný řetězec.  github-32444a99dc2bd60e06b9dd497b0e5fd2ffd6f85165e93c589c165f75bedcf718.js:7:28475
Zdroj na „https://www.google-analytics.com/collect“ byl zablokován, protože je povolena ochrana proti sledování.[Learn More] pontoon-tools
this._recipeManager is null  LoginManagerParent.jsm:102
Žádost Cross-Origin zablokována: zásada stejného původu neumožňuje načtení vzdáleného zdroje na ‘https://collector.githubapp.com/collect’. (Důvod: Ověření není podporováno, pokud CORS header ‘Access-Control-Allow-Origin’ je ‘*’).  (unknown)
TypeError: this.keysList is null[Learn More] masterpasswordplusCore.jsm:912:7
can't convert undefined to object  TeamInfoPopup.js:69
TypeError: this.keysList is null[Learn More] masterpasswordplusCore.jsm:912:7
TypeError: this.keysList is null[Learn More]  masterpasswordplusCore.jsm:912:7
TypeError: this.keysList is null[Learn More]  masterpasswordplusCore.jsm:912:7
TypeError: this.keysList is null[Learn More]  masterpasswordplusCore.jsm:912:7
TypeError: this.keysList is null[Learn More] masterpasswordplusCore.jsm:912:7
TypeError: this.keysList is null[Learn More] masterpasswordplusCore.jsm:912:7
chrome.i18n.getUILanguage()
"cs_CZ"
```

**Comment by MikkCZ** [comment]
Thank you. That sounds like the locale detection will be a serious problem here... :( I will try to workaround this in #24 soon.
