### ISSUE TITLE
The team switches to first entry and back to the chosen option during reload

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#44]
from @mathjazz
> The "Load from Pontoon" functionality works fine. The only annoyance
is that for a very brief period of time (maybe 100 ms) the value gets
set to the first item on the list ("ach") and only then to what
Pontoon returns (in my case "sl").

The feature has been added in #38. I should probably change the `<select>` updating procedure and set the desired team as part of it, not afterwards.

**Comment by yfdyh000** [comment]
Although this is a flaw, it clearly reminds the get and set up is completed.
