### ISSUE TITLE
Pick the right locale component to report a bug

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#47]
There is a feature that allows you to report l10n bug from the context menu of highlighted text. At this moment, the product is "Mozilla Localization", but the component (locale team) is not set.

First I need to find a source of mapping form the locale code to the right component (note: some teams probably do not have any). Second a question is, whether the component should be according to the team preference, or maybe better detected from the current page locale (that may be a bit harder to find out).

**Comment by MikkCZ** [comment]
@flodolo where do you take the list of Bugzilla components for locales in Transvision, please?

**Comment by flodolo** [comment]
Products: https://l10n.mozilla-community.org/mozilla-l10n-query/?bugzilla=product

If you want the one in www.mozilla.org::L10N (locale field)
https://l10n.mozilla-community.org/mozilla-l10n-query/?bugzilla=www
