### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#81]
Document usage and features.

blocks #79

**Comment by MikkCZ** [comment]
Hi @flodolo . Do you think I should place documentation of Pontoon Tools for users to [localizer-documentation](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/), or better somewhere else for now (MozillaWiki, markdown files, ...)?

**Comment by flodolo** [comment]
What about using the Wiki page on the GitHub project itself?

**Comment by MikkCZ** [comment]
Good idea. I never used GH wiki, so I forgot the option even exists.

**Comment by MikkCZ** [comment]
For start I have migrated the current wiki pages from MozillaWiki [here](https://github.com/MikkCZ/pontoon-tools/wiki).
