### ISSUE TITLE
Links in notifications are removed in the add-on popup

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#83]
### Steps to reproduce

1. Have a notification containing <a> link.
2. Open Pontoon Tools popup.
3. The notification text is missing the <a> link.

Here an example notification from @flodolo about Notes.
![snimek z 2018-06-27 18-18-08](https://user-images.githubusercontent.com/3941344/41986497-9ab6109a-7a36-11e8-99e2-1e5aa9a29610.png)

**Comment by flodolo** [comment]
More important than the missing anchor, it lost all HTML formatting, making it really hard to read.

**Comment by MikkCZ** [comment]
Both are the effect of using `textContent` of the element only. `innerHTML` is not safe, but we need to trust the content from Pontoon.

@mathjazz is there some sanitization on Pontoon side itself, so it's safe to include the HTML as is?

**Comment by adngdb** [comment]
If Pontoon is exposing unsafe HTML, then we have bigger problems that we need to solve as soon as possible. :-P So yeah, you should be able to trust HTML rendered on Pontoon. As far as I know we don't have any XSS bugs filed at the moment, and our usage of django means, unless we do something specific, all HTML is safe by default.

**Comment by mathjazz** [comment]
Just confirming that we bleach notifications:

https://github.com/mozilla/pontoon/blob/577ec3d77fe9c46ece752edb7bb5a3beb27a5cbd/pontoon/projects/forms.py#L7

https://github.com/mozilla/pontoon/blob/c6d6fa006e73806bc2377f735e36a4637f05143c/pontoon/base/forms.py#L21

**Comment by MikkCZ** [comment]
Fixed in version 3.2.1, which is now available on AMO (and soon will be on Chrome Web Store too).
