### ISSUE TITLE
Use React for the intro page

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#85]
The introduction (tour) page is really simple at this moment, and independent on the rest of the add-on. That makes it really nice piece for rewriting to React and to test other technologies that are about to land in Pontoon with Translate.Next.
- https://github.com/mozilla/pontoon/pull/989
- https://github.com/adngdb/pontoon/blob/translate.next/frontend/README.md
- ESlint: https://github.com/mozilla/pontoon/blob/master/.eslintrc.js

**Comment by adngdb** [comment]
Hey, I discovered you had a tour feature in your addon. @VishalCR7 (one of our GSoC students) is currently working on such a feature for Pontoon itself. Maybe you'll want to chat with him to see where he's heading and avoid duplicate work?

**Comment by VishalCR7** [comment]
Hey @MikkCZ. :-) @adngdb  I think that's pontoon-tools tour what you are talking about here (making users familiar with the pontoon add-on)  and what I'm working on currently is a pontoon tour (making user familiar with pontoon web-app). I cannot figure out if it can lead to duplicate work of any kind according to my limited knowledge but still I would like to know and see if my work on pontoon tour can be of any use here.

**Comment by MikkCZ** [comment]
Hey guys. The current Pontoon Tools intro is designed to mimic the Firefox intro tour introduced with Quantum release on the home/new tab page. I am currently in more like PTO mode this week because of public holidays, but I will get back to you @VishalCR7 during the next week to find out, what the tour in Pontoon will look like and whether there is a space to reuse each others work.
