### ISSUE TITLE
Container tabs required to use Pontoon Tools?

### ISSUE THREAD

**Issue by flodolo** [MikkCZ/pontoon-tools#94]
Just noticed today in Nightly 63.0a1 (2018-08-11) (64 bit): preferences claim that Container tabs are required in order to use Pontoon Tools. Is that really the case or a bug in Firefox permissions?

**Comment by MikkCZ** [comment]
Hi @flodolo.

It's not a bug, it's a feature. No jokes, it was added in #71. :) I wanted to make the permission optional, however Firefox does support contextual identities (container tabs) as required permission only. I have filed a request to Bugzilla to support it as optional too. When it's implemented and Pontoon Tools updated, you should not see that again in Firefox preferences, until you use that feature.

**Comment by flodolo** [comment]
So, just to understand: you need this permission in order to make the add-on work in a container, or am I completely off?

**Comment by MikkCZ** [comment]
Yes. The permission is necessary if you use Pontoon in a container. Without the permission, add-ons can access and fetch data with cookies from the default (no) container only.

**Comment by MikkCZ** [comment]
An example: on my work computer I sometimes check Pontoon when I have some spare time between meetigs. As I open all non-work related in a Personal container, Pontoon Tools was unable to refresh data periodically.

**Comment by flodolo** [comment]
Thanks, it makes more sense now 👍
