### ISSUE TITLE
Pontoon's API seems to have changed a bit

### ISSUE THREAD

**Issue by Djfe** [MikkCZ/pontoon-tools#96]
Somehow the addon doesn't detect correctly anymore, when I'm logged in.
It asks me every 15Minutes (refresh timer) to relog, but it's enough to visit pontoon in a tab to refresh that status.

Also: it doesn't mark notifications as read anymore.
I can click on the button but on the website itself the notifications are still marked as unread (until I watch them). After 15Minutes the addon loads the notifications therefore again as unread.

It's still able to to receive the notifications though, so that part is working :)

Regards

**Comment by MikkCZ** [comment]
Thank you @Djfe for spotting this. I think I saw it yesterday too, but did not have time to debug it. I will do by best to fix it during the weekend.

A quick investigation showed me the request done by Pontoon Tools to fetch notifications from Pontoon is missing cookies, so the behaviour is like you are not logged in. The change is (most likely) not in Pontoon, but in Firefox. Do you also use Nightly? For me everything works in stable, but not in Nightly.

**Comment by MikkCZ** [comment]
The is likely caused resolution of [Bug 1405971](https://bugzilla.mozilla.org/show_bug.cgi?id=1405971)/[Bug 1507814](https://bugzilla.mozilla.org/show_bug.cgi?id=1507814), or something related, or mabye some change in tracking protection behaviour.

Pontoon Tools internally validate the request before attaching the cookie and one of the criteria is the `Origin` header. However I think I can simplify the validation and safely stop using the header.

**Comment by MikkCZ** [comment]
Version 3.4.2 with the fix is on AMO. Please check for add-ons updates in the Add-ons Manager (`Ctrl+Shift+A` > `⚙` gear button in the top right).
